/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.infosys.serviceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the job_register service. Represents a row in the &quot;job_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.infosys.serviceBuilder.model.impl.job_registerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.infosys.serviceBuilder.model.impl.job_registerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see job_register
 * @generated
 */
@ProviderType
public interface job_registerModel extends BaseModel<job_register> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job_register model instance should use the {@link job_register} interface instead.
	 */

	/**
	 * Returns the primary key of this job_register.
	 *
	 * @return the primary key of this job_register
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this job_register.
	 *
	 * @param primaryKey the primary key of this job_register
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the position of this job_register.
	 *
	 * @return the position of this job_register
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this job_register.
	 *
	 * @param position the position of this job_register
	 */
	public void setPosition(String position);

	/**
	 * Returns the archive of this job_register.
	 *
	 * @return the archive of this job_register
	 */
	public boolean getArchive();

	/**
	 * Returns <code>true</code> if this job_register is archive.
	 *
	 * @return <code>true</code> if this job_register is archive; <code>false</code> otherwise
	 */
	public boolean isArchive();

	/**
	 * Sets whether this job_register is archive.
	 *
	 * @param archive the archive of this job_register
	 */
	public void setArchive(boolean archive);

}