/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.infosys.serviceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the staff_roster service. Represents a row in the &quot;staff_roster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.infosys.serviceBuilder.model.impl.staff_rosterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.infosys.serviceBuilder.model.impl.staff_rosterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see staff_roster
 * @generated
 */
@ProviderType
public interface staff_rosterModel extends BaseModel<staff_roster> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff_roster model instance should use the {@link staff_roster} interface instead.
	 */

	/**
	 * Returns the primary key of this staff_roster.
	 *
	 * @return the primary key of this staff_roster
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this staff_roster.
	 *
	 * @param primaryKey the primary key of this staff_roster
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the worker_id of this staff_roster.
	 *
	 * @return the worker_id of this staff_roster
	 */
	public int getWorker_id();

	/**
	 * Sets the worker_id of this staff_roster.
	 *
	 * @param worker_id the worker_id of this staff_roster
	 */
	public void setWorker_id(int worker_id);

	/**
	 * Returns the last_name of this staff_roster.
	 *
	 * @return the last_name of this staff_roster
	 */
	@AutoEscape
	public String getLast_name();

	/**
	 * Sets the last_name of this staff_roster.
	 *
	 * @param last_name the last_name of this staff_roster
	 */
	public void setLast_name(String last_name);

	/**
	 * Returns the first_name of this staff_roster.
	 *
	 * @return the first_name of this staff_roster
	 */
	@AutoEscape
	public String getFirst_name();

	/**
	 * Sets the first_name of this staff_roster.
	 *
	 * @param first_name the first_name of this staff_roster
	 */
	public void setFirst_name(String first_name);

	/**
	 * Returns the middle_name of this staff_roster.
	 *
	 * @return the middle_name of this staff_roster
	 */
	@AutoEscape
	public String getMiddle_name();

	/**
	 * Sets the middle_name of this staff_roster.
	 *
	 * @param middle_name the middle_name of this staff_roster
	 */
	public void setMiddle_name(String middle_name);

	/**
	 * Returns the birth_date of this staff_roster.
	 *
	 * @return the birth_date of this staff_roster
	 */
	public Date getBirth_date();

	/**
	 * Sets the birth_date of this staff_roster.
	 *
	 * @param birth_date the birth_date of this staff_roster
	 */
	public void setBirth_date(Date birth_date);

	/**
	 * Returns the position of this staff_roster.
	 *
	 * @return the position of this staff_roster
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this staff_roster.
	 *
	 * @param position the position of this staff_roster
	 */
	public void setPosition(String position);

	/**
	 * Returns the employment_date of this staff_roster.
	 *
	 * @return the employment_date of this staff_roster
	 */
	public Date getEmployment_date();

	/**
	 * Sets the employment_date of this staff_roster.
	 *
	 * @param employment_date the employment_date of this staff_roster
	 */
	public void setEmployment_date(Date employment_date);

	/**
	 * Returns the salary of this staff_roster.
	 *
	 * @return the salary of this staff_roster
	 */
	public int getSalary();

	/**
	 * Sets the salary of this staff_roster.
	 *
	 * @param salary the salary of this staff_roster
	 */
	public void setSalary(int salary);

	/**
	 * Returns the work_phone_num of this staff_roster.
	 *
	 * @return the work_phone_num of this staff_roster
	 */
	@AutoEscape
	public String getWork_phone_num();

	/**
	 * Sets the work_phone_num of this staff_roster.
	 *
	 * @param work_phone_num the work_phone_num of this staff_roster
	 */
	public void setWork_phone_num(String work_phone_num);

	/**
	 * Returns the mobile_phone_num of this staff_roster.
	 *
	 * @return the mobile_phone_num of this staff_roster
	 */
	@AutoEscape
	public String getMobile_phone_num();

	/**
	 * Sets the mobile_phone_num of this staff_roster.
	 *
	 * @param mobile_phone_num the mobile_phone_num of this staff_roster
	 */
	public void setMobile_phone_num(String mobile_phone_num);

	/**
	 * Returns the bank of this staff_roster.
	 *
	 * @return the bank of this staff_roster
	 */
	@AutoEscape
	public String getBank();

	/**
	 * Sets the bank of this staff_roster.
	 *
	 * @param bank the bank of this staff_roster
	 */
	public void setBank(String bank);

	/**
	 * Returns the archive of this staff_roster.
	 *
	 * @return the archive of this staff_roster
	 */
	public boolean getArchive();

	/**
	 * Returns <code>true</code> if this staff_roster is archive.
	 *
	 * @return <code>true</code> if this staff_roster is archive; <code>false</code> otherwise
	 */
	public boolean isArchive();

	/**
	 * Sets whether this staff_roster is archive.
	 *
	 * @param archive the archive of this staff_roster
	 */
	public void setArchive(boolean archive);

}